[2025-04-05T11:32:19.364+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.analysis_task manual__2025-04-05T11:06:02.963772+00:00 [queued]>
[2025-04-05T11:32:19.619+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.analysis_task manual__2025-04-05T11:06:02.963772+00:00 [queued]>
[2025-04-05T11:32:19.619+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T11:32:19.619+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-05T11:32:19.620+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T11:32:19.970+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): analysis_task> on 2025-04-05 11:06:02.963772+00:00
[2025-04-05T11:32:20.084+0000] {standard_task_runner.py:55} INFO - Started process 179 to run task
[2025-04-05T11:32:20.121+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'analysis_task', 'manual__2025-04-05T11:06:02.963772+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmpulvjqqh3']
[2025-04-05T11:32:20.147+0000] {standard_task_runner.py:83} INFO - Job 140: Subtask analysis_task
[2025-04-05T11:32:20.536+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.analysis_task manual__2025-04-05T11:06:02.963772+00:00 [running]> on host 6b8756d9239f
[2025-04-05T11:32:21.311+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=analysis_task
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T11:06:02.963772+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T11:06:02.963772+00:00
[2025-04-05T11:32:23.247+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 46, in do_analysis
    rows = bq_client.query(query).result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: symbol at [2:12]

Location: us-central1
Job ID: a8264df8-0876-4ef2-a0d3-64d55eb5a158

[2025-04-05T11:32:23.284+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=alpha_vantage_pipeline, task_id=analysis_task, execution_date=20250405T110602, start_date=20250405T113219, end_date=20250405T113223
[2025-04-05T11:32:23.841+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 140 for task analysis_task (400 Unrecognized name: symbol at [2:12]

Location: us-central1
Job ID: a8264df8-0876-4ef2-a0d3-64d55eb5a158
; 179)
[2025-04-05T11:32:24.185+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T11:32:24.603+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
