[2025-04-05T08:34:08.274+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [queued]>
[2025-04-05T08:34:08.303+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [queued]>
[2025-04-05T08:34:08.304+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:34:08.305+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-05T08:34:08.305+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:34:08.346+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-04-05 08:27:20.422995+00:00
[2025-04-05T08:34:08.372+0000] {standard_task_runner.py:55} INFO - Started process 184 to run task
[2025-04-05T08:34:08.382+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'dbt_run', 'manual__2025-04-05T08:27:20.422995+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmpgcug4kn2']
[2025-04-05T08:34:08.390+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask dbt_run
[2025-04-05T08:34:08.610+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [running]> on host 82b3f05c6a94
[2025-04-05T08:34:09.035+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T08:27:20.422995+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T08:27:20.422995+00:00
[2025-04-05T08:34:21.374+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 28, in dbt_run
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.
[2025-04-05T08:34:21.414+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=alpha_vantage_pipeline, task_id=dbt_run, execution_date=20250405T082720, start_date=20250405T083408, end_date=20250405T083421
[2025-04-05T08:34:21.503+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 62 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.; 184)
[2025-04-05T08:34:21.570+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T08:34:21.641+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
