[2025-04-05T08:27:33.526+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [queued]>
[2025-04-05T08:27:33.534+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [queued]>
[2025-04-05T08:27:33.535+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:27:33.535+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-05T08:27:33.535+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:27:33.547+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-04-05 08:27:20.422995+00:00
[2025-04-05T08:27:33.556+0000] {standard_task_runner.py:55} INFO - Started process 522 to run task
[2025-04-05T08:27:33.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'dbt_run', 'manual__2025-04-05T08:27:20.422995+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmpq5okthjh']
[2025-04-05T08:27:33.560+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask dbt_run
[2025-04-05T08:27:33.620+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T08:27:20.422995+00:00 [running]> on host 7f1c65875bfa
[2025-04-05T08:27:33.686+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T08:27:20.422995+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T08:27:20.422995+00:00
[2025-04-05T08:27:36.649+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 28, in dbt_run
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.
[2025-04-05T08:27:36.662+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=alpha_vantage_pipeline, task_id=dbt_run, execution_date=20250405T082720, start_date=20250405T082733, end_date=20250405T082736
[2025-04-05T08:27:36.677+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.; 522)
[2025-04-05T08:27:36.708+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T08:27:36.733+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
