[2025-04-05T06:22:28.668+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.spark_transform scheduled__2025-04-05T05:30:00+00:00 [queued]>
[2025-04-05T06:22:28.677+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.spark_transform scheduled__2025-04-05T05:30:00+00:00 [queued]>
[2025-04-05T06:22:28.678+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T06:22:28.678+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-05T06:22:28.678+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T06:22:28.716+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): spark_transform> on 2025-04-05 05:30:00+00:00
[2025-04-05T06:22:28.731+0000] {standard_task_runner.py:55} INFO - Started process 266 to run task
[2025-04-05T06:22:28.734+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'spark_transform', 'scheduled__2025-04-05T05:30:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmpexmxzq0n']
[2025-04-05T06:22:28.736+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask spark_transform
[2025-04-05T06:22:28.841+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.spark_transform scheduled__2025-04-05T05:30:00+00:00 [running]> on host fc048f88441f
[2025-04-05T06:22:28.932+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=spark_transform
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T05:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-05T05:30:00+00:00
[2025-04-05T06:22:29.062+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 19, in spark_transform
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['spark-submit', '--master', 'spark://spark:7077', '/opt/airflow/scripts/transform_data.py']' returned non-zero exit status 1.
[2025-04-05T06:22:29.080+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=alpha_vantage_pipeline, task_id=spark_transform, execution_date=20250405T053000, start_date=20250405T062228, end_date=20250405T062229
[2025-04-05T06:22:29.099+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task spark_transform (Command '['spark-submit', '--master', 'spark://spark:7077', '/opt/airflow/scripts/transform_data.py']' returned non-zero exit status 1.; 266)
[2025-04-05T06:22:29.114+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T06:22:29.139+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
