[2025-04-05T08:35:16.513+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run scheduled__2025-04-05T08:00:00+00:00 [queued]>
[2025-04-05T08:35:16.520+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run scheduled__2025-04-05T08:00:00+00:00 [queued]>
[2025-04-05T08:35:16.521+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:35:16.521+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-05T08:35:16.521+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T08:35:16.532+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-04-05 08:00:00+00:00
[2025-04-05T08:35:16.540+0000] {standard_task_runner.py:55} INFO - Started process 210 to run task
[2025-04-05T08:35:16.543+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'dbt_run', 'scheduled__2025-04-05T08:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmp3kfxgens']
[2025-04-05T08:35:16.544+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask dbt_run
[2025-04-05T08:35:16.603+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.dbt_run scheduled__2025-04-05T08:00:00+00:00 [running]> on host 82b3f05c6a94
[2025-04-05T08:35:16.729+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-04-05T08:00:00+00:00
[2025-04-05T08:35:19.288+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 28, in dbt_run
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.
[2025-04-05T08:35:19.300+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=alpha_vantage_pipeline, task_id=dbt_run, execution_date=20250405T080000, start_date=20250405T083516, end_date=20250405T083519
[2025-04-05T08:35:19.312+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '/opt/airflow/dbt', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.; 210)
[2025-04-05T08:35:19.340+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T08:35:19.364+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
