[2025-04-05T07:50:59.670+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T07:45:41.181718+00:00 [queued]>
[2025-04-05T07:50:59.677+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T07:45:41.181718+00:00 [queued]>
[2025-04-05T07:50:59.677+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T07:50:59.677+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-05T07:50:59.678+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-05T07:50:59.689+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): dbt_run> on 2025-04-05 07:45:41.181718+00:00
[2025-04-05T07:50:59.696+0000] {standard_task_runner.py:55} INFO - Started process 513 to run task
[2025-04-05T07:50:59.699+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_pipeline', 'dbt_run', 'manual__2025-04-05T07:45:41.181718+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_pipeline.py', '--cfg-path', '/tmp/tmplplzp5bb']
[2025-04-05T07:50:59.700+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask dbt_run
[2025-04-05T07:50:59.760+0000] {task_command.py:388} INFO - Running <TaskInstance: alpha_vantage_pipeline.dbt_run manual__2025-04-05T07:45:41.181718+00:00 [running]> on host 4df01a1500d3
[2025-04-05T07:50:59.824+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=alpha_vantage_pipeline
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2025-04-05T07:45:41.181718+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-05T07:45:41.181718+00:00
[2025-04-05T07:51:02.487+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/alpha_vantage_pipeline.py", line 28, in dbt_run
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dbt', 'run', '--profiles-dir', '.', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.
[2025-04-05T07:51:02.498+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=alpha_vantage_pipeline, task_id=dbt_run, execution_date=20250405T074541, start_date=20250405T075059, end_date=20250405T075102
[2025-04-05T07:51:02.509+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task dbt_run (Command '['dbt', 'run', '--profiles-dir', '.', '--project-dir', '/opt/airflow/dbt']' returned non-zero exit status 2.; 513)
[2025-04-05T07:51:02.529+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-05T07:51:02.559+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
